config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"
  resources :logo_imagems do
    delete 'logo_imagems/:id/apagar_foto', to: 'logo_imagems#apagar_foto', as: :apagar_foto_logo_imagem
  end
  
  resources :tipos_servicos do
    collection do 
      get 'new_modal', to: 'tipos_servicos#new_tipo_modal' 
    end
  end
  
  resources :users do
    get :json_teste, on: :collection
  end

  resources :despesas do
    get :produtos, on: :collection
    get :geral, on: :collection
    get :vale, on: :collection
    get :mensal, on: :collection

  end

  resources :servicos do
    get :todos, on: :collection
    get :mensal, on: :collection
    get :recibo
    
    delete 'servicos/:id/apagar_foto', to: 'servicos#apagar_foto', as: :apagar_foto_servico

  end

  resources :financas do
    get :mensal, on: :collection
    get :individual, on: :collection
  end


  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_logged_in_user
  def index
    @nome = "Wiron"
    @servicos = Servico.all
    @despesas = Despesa.all
    @servicos_total = @servicos.where(data: Time.now.beginning_of_month..Time.now.end_of_month).where(pago: :true).map(&:valor).sum
    @servicos_total_modal = @servicos.where(data: Time.now.beginning_of_month..Time.now.end_of_month).where(pago: :true)
    @servicos_lucro = @servicos_total - @despesas.where(data: Time.now.beginning_of_month..Time.now.end_of_month).sum(:valor)
    @servicos_quantidade_mes = @servicos.where(data: Time.now.beginning_of_month..Time.now.end_of_month).count
    @servicos_pago_pendedente = @servicos.where(data: Time.now.beginning_of_month..Time.now.end_of_month).where(pago: :false).count
    @despesas_mes = @despesas.where(data: Time.now.beginning_of_month..Time.now.end_of_month).sum(:valor)
    @despesas_mes_modal = @despesas.where(data: Time.now.beginning_of_month..Time.now.end_of_month)

    @ultimos_servicos = @servicos.order(data: :desc).limit(3)
    @ultimos_despesas = @despesas.order(data: :desc).limit(3)
    
    
    
    start_date = 3.months.ago.beginning_of_month
    end_date = Time.now.end_of_month
      
      services_data = Servico
        .select("DATE_TRUNC('month', data) as month, COUNT(*) as count, SUM(valor) as total")
        .where(data: start_date..end_date, pago: true)
        .group("1")
        .order("1")

      expenses_data = Despesa
        .select("DATE_TRUNC('month', data) as month, SUM(valor) as total")
        .where(data: start_date..end_date)
        .group("1")
        .order("1")

      merged_data = services_data.map do |service|
        expenses = expenses_data.find { |expense| expense.month == service.month }
        expenses_total = expenses ? expenses.total : 0
        { month: service.month, count: service.count, total: service.total, expenses: expenses_total }
      end

      @categories = merged_data.map { |s| I18n.l(s[:month], format: '%B') }
      @services_data = merged_data.map { |s| s[:count] }
      @profit_data = merged_data.map { |s| s[:total] - s[:expenses] }
      @expenses_data = merged_data.map { |s| s[:expenses] }
  end
end

app/views/static_pages/index.html.erb
<div class="mt-3 text-center ">
  <div class="mb-3"><h2 class="">CADASTRAR</h2></div>
  <div class="row gap-3 d-flex justify-content-center">
    <%= link_to ' Serviços', new_servico_path, class:'btn btn-primary bi bi-stars shadow btn-tremer', style:'width: 10rem; height: 6rem; font-size: 1.73rem' %>
    <%= link_to ' Produtos', produtos_despesas_path, class:'btn btn-primary bi bi-box-seam shadow btn-tremer', style:'width: 10rem; height: 6rem; font-size: 1.65rem' %>
    <%= link_to ' Despesas', despesas_path, class:'btn btn-primary bi bi-dash-circle shadow btn-tremer', style:'width: 10rem; height: 6rem; font-size: 1.6rem' %>
    <%= link_to ' Usuários', new_user_path, class:'btn btn-primary bi bi-person-add shadow btn-tremer', style:'width: 10rem; height: 6rem; font-size: 1.7rem' %>
    <%= link_to ' T.Serviços', new_tipos_servico_path, class:'btn btn-primary bi bi-database-add shadow btn-tremer', style:'width: 10rem; height: 6rem; font-size: 1.7rem' %>
  </div>  
</div>
<div class="mt-5 text-center mb-3">
  <div class="mb-3"><h2 class="">ACOMPANHAMENTO MENSAL</h2></div>
  <div class="row gap-3 d-flex justify-content-center">
    <div class="card shadow text-center text-bg-success" style="width: 12rem"
      data-bs-toggle="tooltip" data-bs-placement="left"
        data-bs-custom-class="custom-tooltip"
        data-bs-title="Valor total arrecadado no mês.">
        <button type="button" class="text-bg-success" style="border: none !important" data-bs-toggle="modal" data-bs-target="#total">
          <h5 class="card-header">Valor total</h5>
          <div class="card-body">
            <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= numero_real(@servicos_total,2) %></h5>
          </div>
        </button>
    </div>
    <div class="card shadow text-center text-bg-primary" style="width: 12rem"
      data-bs-toggle="tooltip" data-bs-placement="bottom"
        data-bs-custom-class="custom-tooltip"
        data-bs-title="Valor lucro arrecadado no mês.">
        
          <h5 class="card-header">Valor lucro</h5>
          <div class="card-body">
            <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= numero_real(@servicos_lucro,2) %></h5>
          </div>
        
    </div>
      <div class="card shadow text-center text-bg-danger" style="width: 12rem"
        data-bs-toggle="tooltip" data-bs-placement="bottom"
          data-bs-custom-class="custom-tooltip"
          data-bs-title="Valor despesas no mês.">
        <button type="button" class="text-bg-danger" style="border: none !important" data-bs-toggle="modal" data-bs-target="#despesas">
          <h5 class="card-header">Despesas</h5>
          <div class="card-body">
            <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= numero_real(@despesas_mes,2) %></h5>
          </div>
        </button>
      </div>
    <div class="card shadow text-center text-bg-secondary" style="width: 12rem"
        data-bs-toggle="tooltip" data-bs-placement="bottom"
        data-bs-custom-class="custom-tooltip"
        data-bs-title="Quantidade de serviços mensal.">
      <h5 class="card-header" style="font-size: 1.2rem">Quantidade</h5>
      <div class="card-body">
        <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000; font-size: 1rem"><%= pluralize(@servicos_quantidade_mes, 'serviço', 'serviços') %></h5>
      </div>
    </div>
    <div class="card shadow text-center text-bg-danger" style="width: 12rem"
        data-bs-toggle="tooltip" data-bs-placement="right"
        data-bs-custom-class="custom-tooltip"
        data-bs-title="Serviços que não foi marcado o pagamento.">
    <h5 class="card-header" style="font-size: 1.2rem" >Pagamento</h5>
    <div class="card-body">
      <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000; font-size: 1rem" ><%= pluralize( @servicos_pago_pendedente , 'pendente', 'pendentes') %></h5>
    </div>
  </div>
  </div>
</div>

<!-- Modal despesa -->
<div class="modal fade" id="despesas" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Detalhes das despesas</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% @despesas_mes_modal.each do |despesa| %> 
          <b><%= despesa.tipo %></b>
          <%= despesa.tipo == "VALE" ?  despesa.user.nome.upcase + " - " + " " + numero_real(despesa.valor,2) : " - " + numero_real(despesa.valor,2) %><br>
        <% end %><br>
        <%= numero_real(@despesas_mes,2) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal total -->
<div class="modal fade" id="total" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Detalhes dos lucros</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
         <% @servicos_total_modal.each do |servico| %> 
          <b><%= servico.cliente.upcase %></b> - 
          <%= servico.servico.upcase %> - 
          <%= numero_real(servico.valor,2) %><br>
        <% end %><br>
        <%= numero_real(@servicos_total,2) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center mt-5 gap-3 flex-wrap">
  <div class="card shadow text-center text-bg-" style="width: 22rem">
    <h5 class="card-header">Ultimos serviços</h5>
    <div class="">
      <div class="card-body">
        <h6 class="card-title fw-bold" >
        <% @ultimos_servicos.each do |servico| %>
          <%= servico.cliente.upcase %> - 
          <%= servico.veiculo.upcase %> - <%= numero_real(servico.valor,2) %><br>
        <% end %>
        </h6>
      </div>
    </div>
  </div>
  <div class="card shadow text-center text-bg-" style="width: 22rem">
    <h5 class="card-header">Ultimas despesas</h5>
    <div class="">
      <div class="card-body">
        <h6 class="card-title fw-bold" >
        <% @ultimos_despesas.each do |despesas| %>
          <%= despesas.observacao.upcase %> - 
          <%= despesas.vale != nil ? despesas.vale : '' %> <%= despesas.tipo == "FUNCIONÁRIO" ? despesas.user.nome.upcase : '' %> - <%= numero_real(despesas.valor,2) %><br>
        <% end %>
        </h6>
      </div>
    </div>
  </div>
</div>

<div class="mt-5 mb-4 card p-4 shadow">
  
  <div id="chart"></div>

  <%= javascript_tag do %>
    $(document).ready(function() {
      var chart = new Highcharts.Chart({
        credits: {
          enabled: false
        },
        lang: {
          printChart: "Imprimir gráfico",
          downloadPNG: "Baixar como PNG",
          downloadJPEG: "Baixar como JPEG",
          downloadPDF: "Baixar como PDF",
          downloadSVG: "Baixar como SVG",
          contextButtonTitle: "Opções de exportação do gráfico",
          viewFullscreen: "Ver gráfico em tela cheia",
          exitFullscreen: "Sair tela cheia"
        },
        chart: {
          renderTo: 'chart',
          type: 'column'
        },
        title: {
          text: 'Quantidade de serviços e lucro dos últimos meses'
        },
        xAxis: {
          categories: <%= raw @categories %>
        },
        yAxis: [{
          title: {
            text: 'Quantidade de serviços'
          }
        }, {
          opposite: true,
          title: {
            text: 'Lucro'
          }
        }],
        series: [{
          name: 'Quantidade de serviços',
          data: <%= raw @services_data %>,
          yAxis: 0
        }, {
          name: 'Lucro',
          data: <%= raw @profit_data %>,
          yAxis: 1,
          tooltip: {
            valuePrefix: 'R$'
          }
        }]
      });
    });
  <% end %>

</div>



<script>
$(document).ready(function() {
  $('.btn-tremer').click(function(e) {
    e.preventDefault(); // Evita que o link seja seguido imediatamente
    var link = $(this).attr('href');
    $('body').fadeOut(300, function() { // Adiciona uma animação de desaparecimento suave na página atual
      setTimeout(function() {
        window.location.href = link; // Redireciona para o link após o atraso
      }, 100); // Define o atraso para 1 segundo (1000ms)
    });
  });
});

var tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
var tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>