config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"
  resources :logo_imagems do
    delete 'logo_imagems/:id/apagar_foto', to: 'logo_imagems#apagar_foto', as: :apagar_foto_logo_imagem
  end
  
  resources :tipos_servicos do
    collection do 
      get 'new_modal', to: 'tipos_servicos#new_tipo_modal' 
    end
  end
  
  resources :users do
    get :json_teste, on: :collection
  end

  resources :despesas do
    get :produtos, on: :collection
    get :geral, on: :collection
    get :vale, on: :collection
    get :mensal, on: :collection

  end

  resources :servicos do
    get :todos, on: :collection
    get :mensal, on: :collection
    get :recibo
    
    delete 'servicos/:id/apagar_foto', to: 'servicos#apagar_foto', as: :apagar_foto_servico

  end

  resources :financas do
    get :mensal, on: :collection
    get :individual, on: :collection
  end


  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

end

app/models/servico.rb
class Servico < ApplicationRecord
    validates :cliente, presence: true
    validates :valor, presence: true
    validates :servico, presence: true
    validates :veiculo, presence: true

    has_one_attached :imagem
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_servico, only: %i[ show edit update destroy apagar_foto ]
  include Pagy::Backend
  require 'image_processing/mini_magick'

  # GET /servicos or /servicos.json
  def index
    @servicos = Servico.all.order(:data)
    @servicos_do_dia = @servicos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'")
    @servicos_total = @servicos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").where(pago: :true).map(&:valor).sum
    @servicos_quantidade_diario = @servicos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").count
    @servicos_pago_pendedente = @servicos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").where(pago: :false).count
    @users = User.all.select("id","nome").order(:nome)

    @pagy,  @servicos_do_dia = pagy( @servicos_do_dia)
  end

  def todos
    @servicos = Servico.all.order(:data)
    @servicos_total = @servicos.map(&:valor).sum
    @servicos_quantidade = @servicos.count
    @servicos_pago_pendedente = @servicos.where(pago: :false).count
    @users = User.all.order(:tipo)

    if params[:data_search] || params[:cliente_busca] || params[:caixa_busca]
      @servicos = @servicos.where('cliente ILIKE ?', "%#{params[:cliente_busca]}%") if params[:cliente_busca].present?
      @servicos_pago_pendedente = @servicos.where(pago: :false).count
      if params[:data_search].present?
        params[:data_search] = Date.parse(params[:data_search]).strftime("%Y-%m-%d")
        @servicos = @servicos.where('CAST(data AS TEXT) LIKE ?', "%#{params[:data_search]}%")
        @servicos_total = @servicos.map(&:valor).sum
        @servicos_quantidade = @servicos.count
        @servicos_pago_pendedente = @servicos.where(pago: :false).count
      end
      if params[:caixa_busca] != "SELECIONE CAIXA"
        @servicos = @servicos.where(caixa: params[:caixa_busca])
      end
    end

    @pagy, @servicos = pagy(@servicos)
  end

  def mensal
    @servicos_all = Servico.all.order(:data)
    @servicos = @servicos_all.where(data: Time.now.beginning_of_month..Time.now.end_of_month)
    @servicos_total = @servicos_all.where(data: Time.now.beginning_of_month..Time.now.end_of_month).where(pago: :true).map(&:valor).sum
    @servicos_pago_pendedente = @servicos.where(pago: :false).count
    @users = User.all.order(:tipo)
    
    if params[:mes_select] || params[:cliente_busca] || params[:caixa_busca]
      @mes = params[:mes_select] || Time.now.month
      @servicos = @servicos_all.where("DATE_PART('month', data) = ?", @mes) if params[:mes_select].present?
      @servicos = @servicos_all.where('cliente ILIKE ?', "%#{params[:cliente_busca]}%") if params[:cliente_busca].present?
      if params[:caixa_busca] != "SELECIONE CAIXA"
        @servicos = @servicos.where(caixa: params[:caixa_busca])
      end
      
      @servicos_pago_pendedente = @servicos.where(pago: :false).count

      @servicos_total = @servicos_all.where("DATE_PART('month', data) = ?", @mes).where(pago: :true).map(&:valor).sum
      @servicos_quantidade_mes = @servicos_all.where("DATE_PART('month', data) = ?", @mes).count
    else
      @servicos = @servicos_all.where(data: Time.now.beginning_of_month..Time.now.end_of_month)
      @servicos_quantidade_mes = @servicos_all.where(data: Time.now.beginning_of_month..Time.now.end_of_month).count
      @servicos_pago_pendedente = @servicos.where(pago: :false).count
    end

    @pagy, @servicos = pagy(@servicos)
  end

  def recibo
    @servico = Servico.find(params[:servico_id])
    @logo_imagem = LogoImagem.all.limit(1)
    @logo_imagem = @logo_imagem[0]
  end

  # GET /servicos/1 or /servicos/1.json
  def show
  end

  # GET /servicos/new
  def new
    @servico = Servico.new
    @users = User.all.select("id","nome").order(:nome)
    @tipos_servico = TiposServico.all
  end

  # GET /servicos/1/edit
  def edit
    @users = User.all.select("id","nome").order(:nome)
    @tipos_servico = TiposServico.all
  end

  # POST /servicos or /servicos.json
  def create
    @users = User.all.select("id","nome").order(:nome)
    params[:servico][:valor] = params[:servico][:valor].gsub('R$','').gsub(' ','').gsub('.','')
    @tipos_servico = TiposServico.all
    
    @servico = Servico.new(servico_params)

    if @servico.imagem.present?
      image = MiniMagick::Image.open(params[:servico][:imagem])
      processed_image = ImageProcessing::MiniMagick
        .source(image)
        .resize_to_limit(800, 800)
        .strip
        .quality(80)
        .call

      @servico.imagem.attach(io: processed_image, filename: 'cleanner_image.jpg')
    end

    if @servico.save
      flash[:success] = "Serviço #{@servico.servico.downcase} do veículo #{@servico.veiculo.capitalize} foi criado com sucesso!" 
      redirect_to servicos_path
    else
      render 'new'
    end
    
  end

  # PATCH/PUT /servicos/1 or /servicos/1.json
  def update
    @users = User.all.select("id","nome").order(:nome)
    @tipos_servico = TiposServico.all
    
    params[:servico][:valor] = params[:servico][:valor].gsub('R$','').gsub(' ','').gsub('.','')
   
    if @servico.imagem.present?
      image = MiniMagick::Image.open(params[:servico][:imagem])
      processed_image = ImageProcessing::MiniMagick
        .source(image)
        .resize_to_limit(800, 800)
        .strip
        .quality(80)
        .call

      @servico.imagem.attach(io: processed_image, filename: 'cleanner_image.jpg')
    end
    
      if @servico.update(servico_params)
        flash[:success] = "Serviço atualizado com sucesso!" 
        redirect_to servicos_path
      else
        render 'new'
      end
    
  end

  # DELETE /servicos/1 or /servicos/1.json
  def destroy
    @servico.destroy

    flash[:success] = "Serviço apagado com sucesso!" 
    redirect_to servicos_path
    
  end

  def apagar_foto
    @servico.imagem.purge
    redirect_back(fallback_location: root_path)
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def servico_params
      params.require(:servico).permit(:cliente, :data, :servico, :valor, :caixa, :pago, :veiculo, :imagem)
    end
end

app/helpers/servicos_helper.rb
module ServicosHelper
    include Pagy::Frontend
end

app/views/servicos/_form.html.erb
<%= form_with(model: servico) do |form| %>

<div class="flash-msg hide" ><%= render 'layouts/error_messages', object: form.object %></div>

  <div class="row">
    <div class="col-sm-2">
      <div class="form-group mb-2">
        <%= form.label :data %>
        <%= form.datetime_local_field :data, value: @servico.data.present? ? @servico.data.strftime('%Y-%m-%dT%H:%M') : Time.now.strftime('%Y-%m-%dT%H:%M'), class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="form-group mb-2">
        <%= form.label :cliente %>
        <%= form.text_field :cliente, class: "form-control text-uppercase" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group mb-2">
        <%= form.label :veiculo, 'Veículo' %>
        <%= form.text_field :veiculo, class: "form-control text-uppercase" %>
      </div>
    </div>
    
  </div>
  
  <div class="row">
    <div class="col-sm-3">
      <div class="form-group mb-2">
        <%= form.label :servico, 'Serviço' %>
        <%= form.select :servico, @tipos_servico.map { |t| [t.tipo.upcase] },{}, class: "form-control text-uppercase" %>
      </div>
    </div> 
    <div class="col-sm-2 mt-4">
      <%= link_to "Adicionar Serviço", new_modal_tipos_servicos_path(rota: true), class: "btn btn-primary", data: { bs_toggle: "modal", bs_target: "#tipoServicoModal", remote: true  } %>
    </div>
    <div class="col-sm-2">
      <div class="form-group mb-2">
        <%= form.label :valor %>
        <%= form.text_field :valor, value: params[:action] == 'edit' ? numero_real(@servico.valor,2) : '', class: "form-control moeda" %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="form-group mb-2">
        <%= form.label :caixa %>
        <%= form.select :caixa, [["NORMAL"]] + @users.map { |u| [u.nome.upcase] },{}, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="form-group mt-4">
        <%= form.label :pago %>
        <%= form.check_box :pago, class: "form-check-input" %>
      </div>
    </div>
  </div>


  
  
 
  <div class="card shadow p-3 mt-3 ">
    <div class="form-group ">
      <%= form.label :imagem, 'Imagem do Veículo', class:'mb-2' %>
      <%= form.file_field :imagem, capture: "environment", accept: "image/*", onchange: "showPreview(this);",  class: "form-control", id: "imagem_input"  %>
    </div>

    <div class="mt-3 text-center">
      <%= image_tag '', id: 'preview', class: 'hide ', style:'width: 70%' %>
    </div>

    <div class="p-2 text-center" >
      <% if @servico.imagem.present? %>
        <%= image_tag @servico.imagem, id:'teste_img', width:200 %>
      <% end %>
      <div>
        <%= link_to " Apagar foto", servico_apagar_foto_servico_path(@servico), method: :delete, id: "apagar-foto-link", class:"mt-2 bi bi-trash3 btn btn-danger" if @servico.imagem.present? %>
      </div>
    </div>
  </div>

  <div class="form-group mt-4">
    <%= form.submit "Salvar", class: "btn btn-primary me-2" %>
    <%= link_to "Voltar", servicos_path, class: "btn btn-primary active" %>
  </div>
   
<% end %>


  <!-- modal -->
 
<div class="modal fade" id="tipoServicoModal" tabindex="-1" aria-labelledby="tipoServicoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="tipoServicoModalLabel">Cadastrar novo tipo</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <div id="modalTipoServico">
      </div>
      </div>
    </div>
  </div>
</div>
  <!-- modal -->

 <script>
 
  $(document).ready(function(){
    $('.moeda').maskMoney({
      prefix: 'R$ ',
      decimal: ',',
      thousands: '.'
    });
  });

  function showPreview(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();

    reader.onload = function (e) {
      $('#preview')
        .attr('src', e.target.result)
        .removeClass('hide');
    };

    reader.readAsDataURL(input.files[0]);
  }
  }

  //função pra da o purge na foto
  $(document).ready(function() {
  $('#apagar-foto-link').on('click', function(event) {
    event.preventDefault();

      $.ajax({
        url: url,
        method: 'DELETE',
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        error: function(error) {
          console.error(error);
          alert("Erro ao apagar foto.");
        }
      });
    
  });
});


  </script>

app/views/servicos/edit.html.erb
<h1>Editar Serviço</h1>

<%= render 'form', servico: @servico %>

app/views/servicos/index.html.erb
<div class="float-end">
  <a href="/servicos/new" class=" fs-1 ms-2"><i class="bi bi-plus-circle-fill"></i></a>
  <a href="/servicos/todos" class=" fs-1"><i class="bi bi-filter-circle-fill"></i></a>
</div>

<h1 class="mt-3">Serviços do dia</h1>

<div class=" d-flex justify-content-center mt-5 gap-4 flex-wrap" >
  <div class="card shadow text-center text-bg-primary" style="width: 10rem">
    <h5 class="card-header">Valor</h5>
    <div class="card-body">
      <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= numero_real(@servicos_total,2) %></h5>
    </div>
  </div>
  <div class="card shadow text-center text-bg-secondary   " style="width: 10rem">
    <h5 class="card-header" >Quantidade</h5>
    <div class="card-body">
      <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= pluralize(@servicos_quantidade_diario, 'serviço', 'serviços') %></h5>
    </div>
  </div>
  <div class="card shadow text-center text-bg-danger" style="width: 10rem" >
    <h5 class="card-header" >Pagamento</h5>
    <div class="card-body ">
      <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= pluralize( @servicos_pago_pendedente , 'pendente', 'pendentes') %></h5>
    </div>
  </div>
</div>

 
<div class="mt-4 hide-res">
  <table class="table">
    <thead>
      <tr>
        <th style="width: 5%"></th>
        <th style="width: 10%">Data/Hora</th>
        <th style="">Cliente</th>
        <th style="">Serviço</th>
        <th style="">Veículo</th>
        <th>Caixa</th>
        <th>Valor</th>
        <th>Pago?</th>
        <th>Recibo</th>
        <th >Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @servicos_do_dia.each do |servico| %>
        <tr>
          <td>
            <div class="overflow-hidden" style="width:60px; height:60px"> 
                <%#= image_tag servico.imagem, width:60 if servico.imagem.present? %>
                <%= link_to image_tag(servico.imagem, width:60),servico, style: "text-decoration: none;", class:"text-white",
                data:{ bs_toggle: "modal", bs_target: "#servicoModal#{servico.id}", remote: true } if servico.imagem.present? %>
            </div>
          </td>
          <td>
            <%= servico.data.strftime('%d/%m/%Y') %>
            <div style="font-size:0.7rem"><%= servico.data.strftime('%H:%M') %></div>
          </td>
          <td><%= servico.cliente.upcase %></td>
          <td><%= servico.servico.upcase %></td>
          <td><%= servico.veiculo.upcase %></td>
          <td><%= servico.caixa.upcase %></td>

          <td class="moeda"><%= numero_real(servico.valor, 2) %></td>
          <td>
            <% if servico.pago %>
              <span class="badge rounded-pill bg-success">SIM</span>
            <% else %>
              <span class="badge rounded-pill bg-danger">NÃO</span>
            <% end %>
          </td>
          <td>
            <%= link_to 'GERAR', servico_recibo_path(servico), class:'badge rounded-pill bg-secondary link-limpo' if servico.pago %>
            <%= link_to 'GERAR', '', class:'badge rounded-pill bg-danger link-limpo pe-none' unless servico.pago %>
          </td>
          <td>
            <%#= link_to 'Show', servico %>
            <%= link_to '', edit_servico_path(servico), class:'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6'  %>
            <%= link_to '', servico, method: :delete, class: 'btn btn-danger rounded-pill bi bi-trash3-fill', data: { confirm: 'Apagar?' } %>
          </td>
        </tr>

        <div class="modal fade" id="servicoModal<%= servico.id %>" tabindex="-1" aria-labelledby="servicoLabel<%= servico.id %>" aria-hidden="true">
          <div class="modal-dialog ">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="servicoLabel<%= servico.id %>">Detalhes do serviço</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-center">
                <%= image_tag servico.imagem, width:'80%' if servico.imagem.present? %>
                <div class="mt-2"><span style="font-size: 0.8rem"><b>Cliente:</b> </span><%= servico.cliente.upcase %></div>
                <div><span style="font-size: 0.8rem"><b>Serviço:</b> </span><%= servico.servico.upcase %></div>
                <div><span style="font-size: 0.8rem"><b>Veículo:</b> </span><%= servico.veiculo.upcase %></div>
                <div><span style="font-size: 0.8rem"><b>Caixa:</b> </span><%= servico.caixa.upcase %></div>
                <div><span style="font-size: 0.8rem"><b>Valor:</b> </span><%= numero_real(servico.valor, 2) %></div>
                <div class="mt-2">
                  <% if servico.pago %>
                    <span class="badge rounded-pill bg-success">SERVIÇO PAGO</span>
                  <% else %>
                    <span class="badge rounded-pill bg-danger">PAGAMENTO PENDENTE</span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

      <% end %>
    </tbody>
  </table>
</div>

<div class="hide show-res  ">
  <% @servicos_do_dia.each do |servico| %>
  <div class="d-flex justify-content-center">
    <div class="card  shadow mt-4" style="width: 95%;">
      <div class="card-header" style=" background-color: #e4e4e4;">
      <div class="row" >
        <div class="col-6" >
          <% if servico.imagem.present? %>
            <div class="" >
              <div class="overflow-hidden " style="width:7rem; height:7rem">
                <%= image_tag servico.imagem, width:100  %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="col-6" >
          <% if servico.pago %>
            <div class="badge rounded-pill bg-success fs-3  mt-3 float-end">PAGO</div>
          <% else %>
            <div class="badge rounded-pill bg-danger float-none">PAGAMENTO PENDENTE</div>
          <% end %>

           <div class="mt-2 float-end me-1">
            <%= link_to '', edit_servico_path(servico), class:'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6 shadow'  %>
            <%= link_to '', servico, method: :delete, class: 'btn btn-danger rounded-pill bi bi-trash3-fill shadow', data: { confirm: 'Apagar?' } %>
          </div>
        </div>
      </div>
      </div>

      <div class="text-center mt-2 mb-2">
        
        <div style="font-size: 1rem"><b>Data/Hora: </b> <span class="fs-5"><%= servico.data.strftime('%d/%m/%Y - %H:%M') %></span></div>
        <div style="font-size: 1rem"><b>Cliente: </b> <span class="fs-5"><%= servico.cliente.upcase %></span></div>
        <div style="font-size: 1rem"><b>Serviço: </b> <span class="fs-5"><%= servico.servico.upcase %></span></div>
        <div style="font-size: 1rem"><b>Veículo: </b> <span class="fs-5"><%= servico.veiculo.upcase %></span></div>
        <div style="font-size: 1rem"><b>Caixa: </b> <span class="fs-5"><%= servico.caixa.upcase %></span></div>
        <div style="font-size: 1rem"><b>Valor: </b> <span class="fs-5"><%= numero_real(servico.valor,2) %></span></div>
      </div>
      
    </div>
  </div>
  <% end %>
</div>

<br>

<div class="div-pagy mt-3">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/servicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @servico.cliente %>
</p>

<%= link_to 'Edit', edit_servico_path(@servico) %> |
<%= link_to 'Back', servicos_path %>

app/views/servicos/todos.html.erb
<a href="/servicos/new" class="float-end fs-1"><i class="bi bi-plus-circle-fill"></i></a>
<h1 class="mt-3">Todos serviços</h1>
<div class=" d-flex justify-content-center mt-5 gap-4 flex-wrap" >
  <div class="card shadow text-center text-bg-primary" style="width: 10rem">
    <h5 class="card-header">Valor</h5>
    <div class="card-body">
      <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= numero_real(@servicos_total,2) %></h5>
    </div>
  </div>
  <div class="card shadow text-center text-bg-secondary   " style="width: 10rem">
    <h5 class="card-header" >Quantidade</h5>
    <div class="card-body">
      <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= pluralize(@servicos_quantidade, 'serviço', 'serviços') %></h5>
    </div>
  </div>
  <div class="card shadow text-center text-bg-danger" style="width: 10rem">
    <h5 class="card-header" >Pagamento</h5>
    <div class="card-body">
      <h5 class="card-title fw-bold" style="text-shadow: 1px 1px #000"><%= pluralize( @servicos_pago_pendedente , 'pendente', 'pendentes') %></h5>
    </div>
  </div>
</div>

<%= form_tag todos_servicos_path, method: :get do %>
<div class="row mt-4">
    <div class="col-sm-2 mb-2">
      <input type="date" class="form-control" name="data_search" value="<%= params[:data_search].present? ? params[:data_search] : '' %>">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" class="form-control" name="cliente_busca" placeholder="Nome do cliente">
    </div>
    <div class="col-sm-2 mb-2">
      <%= select_tag :caixa_busca, options_for_select([["SELECIONE CAIXA", "SELECIONE CAIXA"], ["NORMAL", "NORMAL"]] + @users.map { |u| [u.nome.upcase] }, selected: "SELECIONE CAIXA"), class: "form-control" %>
    </div>
    <div class="col-sm-1 mb-2">
      <button type="submit" class="btn btn-primary">Pesquisar</button>
    </div>
    <div class="col-sm-2 mb-2">
    <a href="/servicos/todos/" class="btn btn-primary">Limpar Filtro</a>
    </div>
  </div>
<% end %>


<div class=" mt-4 hide-res">
  <table class="table ">
    <thead>
      <tr>
        <th style=""></th>
        <th style="width: 5%">Data/Hora</th>
        <th style="width: 20%">Cliente</th>
        <th >Serviço</th>
        <th >Veículo</th>
        <th>Caixa</th>
        <th>Valor</th>
        <th>Pago?</th>
        <th>Recibo</th>
        <th >Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @servicos.each do |servico| %>
        <tr>
          <td><div class="overflow-hidden" style="width:60px; height:60px"> <%= image_tag servico.imagem, width:60 if servico.imagem.present? %></div></td>
          <td>
            <%= servico.data.strftime('%d/%m/%Y') %>
            <div style="font-size:0.7rem"><%= servico.data.strftime('%H:%M') %></div>
          </td>
          <td><%= servico.cliente.upcase %></td>
          <td><%= servico.servico.upcase %></td>
          <td><%= servico.veiculo.upcase %></td>
          <td><%= servico.caixa.upcase %></td>
          <td><%= numero_real(servico.valor,2) %></td>
          <td>
            <% if servico.pago %>
              <span class="badge rounded-pill bg-success">sim</span>
            <% else %>
              <span class="badge rounded-pill bg-danger">não</span>
            <% end %>
          </td>
          <td>
            <%= link_to 'GERAR', servico_recibo_path(servico), class:'badge rounded-pill bg-secondary link-limpo' if servico.pago %>
            <%= link_to 'GERAR', '', class:'badge rounded-pill bg-danger link-limpo pe-none' unless servico.pago %>
          </td>
          <td>
            <%#= link_to 'Show', servico %>
            <%= link_to '', edit_servico_path(servico), class:'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6'  %>
            <%= link_to '', servico, method: :delete, class: 'btn btn-danger rounded-pill bi bi-trash3-fill', data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="hide show-res  ">
  <% @servicos.each do |servico| %>
  <div class="d-flex justify-content-center">
    <div class="card  shadow mt-4" style="width: 95%;">
      <div class="card-header" style=" background-color: #e4e4e4;">
      <div class="row" >
        <div class="col-6" >
          <% if servico.imagem.present? %>
            <div class="" >
              <div class="overflow-hidden " style="width:7rem; height:7rem">
                <%= image_tag servico.imagem, width:100  %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="col-6" >
          <% if servico.pago %>
            <div class="badge rounded-pill bg-success fs-3  mt-3 float-end">PAGO</div>
          <% else %>
            <div class="badge rounded-pill bg-danger float-none">PAGAMENTO PENDENTE</div>
          <% end %>

           <div class="mt-2 float-end me-1">
            <%= link_to '', edit_servico_path(servico), class:'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6 shadow'  %>
            <%= link_to '', servico, method: :delete, class: 'btn btn-danger rounded-pill bi bi-trash3-fill shadow', data: { confirm: 'Apagar?' } %>
          </div>
        </div>
      </div>
      </div>

      <div class="text-center mt-2 mb-2">
        
        <div style="font-size: 1rem"><b>Data/Hora: </b> <span class="fs-5"><%= servico.data.strftime('%d/%m/%Y - %H:%M') %></span></div>
        <div style="font-size: 1rem"><b>Cliente: </b> <span class="fs-5"><%= servico.cliente.upcase %></span></div>
        <div style="font-size: 1rem"><b>Serviço: </b> <span class="fs-5"><%= servico.servico.upcase %></span></div>
        <div style="font-size: 1rem"><b>Veículo: </b> <span class="fs-5"><%= servico.veiculo.upcase %></span></div>
        <div style="font-size: 1rem"><b>Caixa: </b> <span class="fs-5"><%= servico.caixa.upcase %></span></div>
        <div style="font-size: 1rem"><b>Valor: </b> <span class="fs-5"><%= numero_real(servico.valor,2) %></span></div>
      </div>
      
    </div>
  </div>
  <% end %>
</div>


<div class="div-pagy mt-3">
  <%== pagy_bootstrap_nav(@pagy) %>
<%= link_to "Voltar", servicos_path, class: "btn btn-primary active mt-3" %>
</div>



<br>