config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"
  resources :logo_imagems do
    delete 'logo_imagems/:id/apagar_foto', to: 'logo_imagems#apagar_foto', as: :apagar_foto_logo_imagem
  end
  
  resources :tipos_servicos do
    collection do 
      get 'new_modal', to: 'tipos_servicos#new_tipo_modal' 
    end
  end
  
  resources :users do
    get :json_teste, on: :collection
  end

  resources :despesas do
    get :produtos, on: :collection
    get :geral, on: :collection
    get :vale, on: :collection
    get :mensal, on: :collection

  end

  resources :servicos do
    get :todos, on: :collection
    get :mensal, on: :collection
    get :recibo
    
    delete 'servicos/:id/apagar_foto', to: 'servicos#apagar_foto', as: :apagar_foto_servico

  end

  resources :financas do
    get :mensal, on: :collection
    get :individual, on: :collection
  end


  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

end

app/models/logo_imagem.rb
class LogoImagem < ApplicationRecord
    has_one_attached :imagem
end

app/controllers/logo_imagems_controller.rb
class LogoImagemsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_logo_imagem, only: %i[ show edit update destroy apagar_foto]

  # GET /logo_imagems or /logo_imagems.json
  def index
    @logo_imagems = LogoImagem.all
  end

  # GET /logo_imagems/1 or /logo_imagems/1.json
  def show
  end

  # GET /logo_imagems/new
  def new
    @logo_imagem = LogoImagem.new
  end

  # GET /logo_imagems/1/edit
  def edit
  end

  # POST /logo_imagems or /logo_imagems.json
  def create
    @logo_imagem = LogoImagem.new(logo_imagem_params)

    if @logo_imagem.save
      flash[:success] = "Logo salva com sucesso!" 
      redirect_to logo_imagems_path
    else
      flash[:danger] = "Logo não foi salva!" 
      redirect_to logo_imagems_path
    end
    
  end

  # PATCH/PUT /logo_imagems/1 or /logo_imagems/1.json
  def update
    if @logo_imagem.update(logo_imagem_params)
      flash[:success] = "Logo editada com sucesso!" 
      redirect_to logo_imagems_path
    else
      flash[:danger] = "Logo não foi editada!" 
      redirect_to logo_imagems_path
    end
  end

  def apagar_foto
    @logo_imagem.imagem.purge
    redirect_back(fallback_location: root_path)
  end

  # DELETE /logo_imagems/1 or /logo_imagems/1.json
  def destroy
    @logo_imagem.destroy

    flash[:success] = "Logo apagada com sucesso!" 
    redirect_to logo_imagems_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo_imagem
      @logo_imagem = LogoImagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def logo_imagem_params
      params.require(:logo_imagem).permit(:imagem, :nome)
    end
end

app/helpers/logo_imagems_helper.rb
module LogoImagemsHelper
end

app/views/logo_imagems/_form.html.erb
<%= form_with(model: logo_imagem) do |form| %>
 <div class="flash-msg hide" ><%= render 'layouts/error_messages', object: form.object %></div>

<div class="card shadow p-3 mt-3 ">
    <div class="form-group mb-3">
      <%= form.label :nome, 'Nome da empresa' %>
      <%= form.text_field :nome, class: "form-control text-uppercase" %>
    </div>

    <div class="form-group ">
      <%= form.label :imagem, 'Selecione o arquivo da logo' %>
      <%= form.file_field :imagem, accept: "image/*", onchange: "showPreview(this);",  class: "form-control", id: "imagem_input"  %>
    </div>

    
    <div class="mt-3 text-center">
      <%= image_tag '', id: 'preview', class: 'hide ', style:'width: 70%' %>
    </div>

    <div class="p-2 text-center" >
      <% if @logo_imagem.imagem.present? %>
        <%= image_tag @logo_imagem.imagem, id:'teste_img', width:300 %>
      <% end %>
      <div>
        <%= link_to " Apagar foto",logo_imagem_apagar_foto_logo_imagem_path(@logo_imagem), method: :delete, id: "apagar-foto-link", class:"mt-2 bi bi-trash3 btn btn-danger" if @logo_imagem.imagem.present? %>
      </div>
    </div>
  </div>

   <div class="form-group mt-4">
    <%= form.submit "Salvar", class: "btn btn-primary me-2" %>
    <%= link_to "Voltar",logo_imagems_path, class: "btn btn-primary active" %>
  </div>
  
<% end %>


<script>
function showPreview(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();

    reader.onload = function (e) {
      $('#preview')
        .attr('src', e.target.result)
        .removeClass('hide');
    };

    reader.readAsDataURL(input.files[0]);
  }
  }

  $(document).ready(function() {
  $('#apagar-foto-link').on('click', function(event) {
    event.preventDefault();

      $.ajax({
        url: url,
        method: 'DELETE',
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        error: function(error) {
          console.error(error);
          alert("Erro ao apagar foto.");
        }
      });
    
  });
});
</script>

app/views/logo_imagems/edit.html.erb
<h1>Editar Logo Imagem</h1>

<%= render 'form', logo_imagem: @logo_imagem %>

app/views/logo_imagems/index.html.erb
<!--<div class="float-end">
  <%= link_to '', new_logo_imagem_path, class:'i bi-plus-circle-fill fs-1 ' %>
</div>-->

<h1>Logotipo</h1>

<% if @logo_imagems.present? %>
  <table class="table">
    <thead>
      <tr>
        <th>Imagem</th>
        <th>Empresa</th>
        <th colspan="3">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @logo_imagems.each do |logo_imagem| %>
        <tr>
        <td>
          <%= image_tag(logo_imagem.imagem, width: 100) if logo_imagem.imagem.present?%>
        </td>
        <td>
          <%= logo_imagem.nome.upcase %>
        </td>
          <td>
            <%= link_to '', edit_logo_imagem_path(logo_imagem), class:'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6'  %>
            <%= link_to '', logo_imagem, method: :delete, class: 'btn btn-danger rounded-pill bi bi-trash3-fill', data: { confirm: 'Apagar?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="mt-3">
    Não tem nenhum logotipo cadastrado no sistema.<br>
    <%= link_to ' Adicionar', new_logo_imagem_path, class:'btn btn-primary bi-plus-circle shadow btn-tremer mt-2', style:'width: 9rem; height: auto !important; font-size: 1.3rem' %>
  </div>
<% end %>

<br>

app/views/logo_imagems/new.html.erb
<h1>Novo Logotipo</h1>

<%= render 'form', logo_imagem: @logo_imagem %>